INSERT INTO "USER" (NAME,EMAIL,PASSWORD,REGISTRERUNGS_DATUM)
VALUES('Test','hui@soset.daniya','12345',SYSDATE);
INSERT INTO "USER" (NAME,EMAIL,PASSWORD,REGISTRERUNGS_DATUM)
VALUES('Jora','hui@soset2.daniya','12345',SYSDATE);
INSERT INTO "USER" (NAME, EMAIL, PASSWORD, REGISTRERUNGS_DATUM) 
VALUES('Anna', 'anna61@web.net', 'CxklFRQl', SYSDATE);
INSERT INTO "USER" (NAME, EMAIL, PASSWORD, REGISTRERUNGS_DATUM) 
VALUES('Tom', 'tom69@example.com', 'w8PU7f65', SYSDATE);
INSERT INTO "USER" (NAME, EMAIL, PASSWORD, REGISTRERUNGS_DATUM)
VALUES('Alex', 'alex46@example.com', '2CEiaeLM', SYSDATE);
INSERT INTO "USER" (NAME, EMAIL, PASSWORD, REGISTRERUNGS_DATUM) 
VALUES('Leo', 'leo83@example.com', '7wJpxRYE', SYSDATE);
INSERT INTO "USER" (NAME, EMAIL, PASSWORD, REGISTRERUNGS_DATUM) 
VALUES('Tom', 'tom66@random.co', 'jisGNu3F', SYSDATE);
INSERT INTO "USER" (NAME, EMAIL, PASSWORD, REGISTRERUNGS_DATUM) 
VALUES('Max', 'max27@example.com', 'drnOvLY0', SYSDATE);
INSERT INTO "USER" (NAME, EMAIL, PASSWORD, REGISTRERUNGS_DATUM) 
VALUES('Alex', 'alex51@random.co', 'tXjC5mOG', SYSDATE);
INSERT INTO "USER" (NAME, EMAIL, PASSWORD, REGISTRERUNGS_DATUM) 
VALUES('Tom', 'tom22@mail.org', 'wGc4TF8X', SYSDATE);
INSERT INTO "USER" (NAME, EMAIL, PASSWORD, REGISTRERUNGS_DATUM) 
VALUES('Lena', 'lena85@random.co', 'D2Z0TaSQ', SYSDATE);
INSERT INTO "USER" (NAME, EMAIL, PASSWORD, REGISTRERUNGS_DATUM) 
VALUES('Sara', 'sara32@mail.org', 'B1w175av', SYSDATE);
INSERT INTO "USER" (NAME, EMAIL, PASSWORD, REGISTRERUNGS_DATUM) 
VALUES('Lena', 'lena25@testmail.com', 'kBlu95xE', SYSDATE);
INSERT INTO "USER" (NAME, EMAIL, PASSWORD, REGISTRERUNGS_DATUM) 
VALUES('Jora', 'jora41@testmail.com', 'UskQD4Fb', SYSDATE);
INSERT INTO "USER" (NAME, EMAIL, PASSWORD, REGISTRERUNGS_DATUM) 
VALUES('Jora', 'jora35@web.net', 'hjOGOLBD', SYSDATE);
INSERT INTO "USER" (NAME, EMAIL, PASSWORD, REGISTRERUNGS_DATUM) 
VALUES('Leo', 'leo82@example.com', 'ajiS7tHA', SYSDATE);
INSERT INTO "USER" (NAME, EMAIL, PASSWORD, REGISTRERUNGS_DATUM) 
VALUES('Sara', 'sara27@testmail.com', 'fhFegp9u', SYSDATE);



INSERT INTO WAEHRUNG (NAME)
VALUES ('USDT');
INSERT INTO WAEHRUNG (NAME)
VALUES ('BTC');
INSERT INTO WAEHRUNG (NAME)
VALUES ('ETH');
INSERT INTO WAEHRUNG (NAME)
VALUES ('SOL');
INSERT INTO WAEHRUNG (NAME)
VALUES ('XRP');

INSERT INTO WALLET (USER_ID, KONTOSTAND ,WAEHRUNG_ID,ADRESSE)
VALUES(1,100.000,1,'uhu123123uh131fklqrz');
INSERT INTO WALLET (USER_ID, KONTOSTAND ,WAEHRUNG_ID,ADRESSE)
VALUES(1,10.30,2,'g0gvl27vJApCvqFmauGu');
INSERT INTO WALLET (USER_ID, KONTOSTAND ,WAEHRUNG_ID,ADRESSE)
VALUES(13,100000,1,'JtxOGGwuvDbDL8L98G8h');
INSERT INTO WALLET (USER_ID, KONTOSTAND ,WAEHRUNG_ID,ADRESSE)
VALUES(8,1.000,4,'LSP7fzHAtx2JPnUCdgnJ');
INSERT INTO WALLET (USER_ID, KONTOSTAND ,WAEHRUNG_ID,ADRESSE)
VALUES(7,0.008463,3,'fij7AFsmq84lTMjNhOi6');
INSERT INTO WALLET (USER_ID, KONTOSTAND ,WAEHRUNG_ID,ADRESSE)
VALUES(5,143534.03244,5,'yjh53acc3HQOOTPcYi9l');

COMMIT;

INSERT INTO PAIR (BASECRYPTO_ID,QUOTECRYPTO_ID,KURS)--USDT-BTC
VALUES (1,2,0.000009513);
INSERT INTO PAIR (BASECRYPTO_ID,QUOTECRYPTO_ID,KURS)--USDT-ETH
VALUES (1,3,0.000300);
INSERT INTO PAIR (BASECRYPTO_ID,QUOTECRYPTO_ID,KURS)--USDT-SOL
VALUES (1,4,0.003893);
INSERT INTO PAIR (BASECRYPTO_ID,QUOTECRYPTO_ID,KURS)--USDT-XRP
VALUES (1,5,0.318461);
INSERT INTO PAIR (BASECRYPTO_ID,QUOTECRYPTO_ID,KURS)--BTC-USDT
VALUES (2,1,105081);
INSERT INTO PAIR (BASECRYPTO_ID,QUOTECRYPTO_ID,KURS)--BTC-ETH
VALUES (2,3,31.5);
INSERT INTO PAIR (BASECRYPTO_ID,QUOTECRYPTO_ID,KURS)--BTC-SOL
VALUES (2,4,409.21);
INSERT INTO PAIR (BASECRYPTO_ID,QUOTECRYPTO_ID,KURS)--BTC-XRP
VALUES (2,5,33420);
INSERT INTO PAIR (BASECRYPTO_ID,QUOTECRYPTO_ID,KURS)--ETH-USDT
VALUES (3,1,3336.16);
INSERT INTO PAIR (BASECRYPTO_ID,QUOTECRYPTO_ID,KURS)--ETH-BTC
VALUES (3,2,0.03174);
INSERT INTO PAIR (BASECRYPTO_ID,QUOTECRYPTO_ID,KURS)--ETH-SOL
VALUES (3,4,12.99);
INSERT INTO PAIR (BASECRYPTO_ID,QUOTECRYPTO_ID,KURS)--ETH-XRP
VALUES (3,5,1060.87);
INSERT INTO PAIR (BASECRYPTO_ID,QUOTECRYPTO_ID,KURS)--SOL-USDT
VALUES (4,1,256.80);
INSERT INTO PAIR (BASECRYPTO_ID,QUOTECRYPTO_ID,KURS)--SOL-BTC
VALUES (4,2,0.002443);
INSERT INTO PAIR (BASECRYPTO_ID,QUOTECRYPTO_ID,KURS)--SOL-ETH
VALUES (4,3, 0.076970);
INSERT INTO PAIR (BASECRYPTO_ID,QUOTECRYPTO_ID,KURS)--SOL-XRP
VALUES (4,5,81.67);
INSERT INTO PAIR (BASECRYPTO_ID,QUOTECRYPTO_ID,KURS)--XRP-USDT
VALUES (5,1,3.14);
INSERT INTO PAIR (BASECRYPTO_ID,QUOTECRYPTO_ID,KURS)--XRP-BTC
VALUES (5,2,0.00002995);
INSERT INTO PAIR (BASECRYPTO_ID,QUOTECRYPTO_ID,KURS)--XRP-ETH
VALUES (5,3,0.000942);
INSERT INTO PAIR (BASECRYPTO_ID,QUOTECRYPTO_ID,KURS)--XRP-SOL
VALUES (5,4,0.012245);
INSERT INTO WALLET (USER_ID, KONTOSTAND ,WAEHRUNG_ID,ADRESSE)
VALUES(1,100.000,1,'uhu123123uh131fklqrz');
INSERT INTO WALLET (USER_ID, KONTOSTAND ,WAEHRUNG_ID,ADRESSE)
VALUES(1,10.30,2,'g0gvl27vJApCvqFmauGu');
INSERT INTO WALLET (USER_ID, KONTOSTAND ,WAEHRUNG_ID,ADRESSE)
VALUES(13,100000,1,'COMMIT;JtxOGGwuvDbDL8L98G8h');
INSERT INTO WALLET (USER_ID, KONTOSTAND ,WAEHRUNG_ID,ADRESSE)
VALUES(8,1.000,4,'LSP7fzHAtx2JPnUCdgnJ');
INSERT INTO WALLET (USER_ID, KONTOSTAND ,WAEHRUNG_ID,ADRESSE)
VALUES(7,0.008463,3,'fij7AFsmq84lTMjNhOi6');
INSERT INTO WALLET (USER_ID, KONTOSTAND ,WAEHRUNG_ID,ADRESSE)
VALUES(5,143534.03244,5,'yjh53acc3HQOOTPcYi9l');


INSERT INTO Investors (Betrag, Waehrung_ID, Start_Datum, Gewinn)
VALUES (1000.00, 1, TO_DATE('2025-01-01', 'YYYY-MM-DD'), 50.00);

INSERT INTO Investors (Betrag, Waehrung_ID, Start_Datum, Gewinn)
VALUES (500.00, 2, TO_DATE('2025-01-05', 'YYYY-MM-DD'), 20.00);

INSERT INTO Investors (Betrag, Waehrung_ID, Start_Datum, Gewinn)
VALUES (750.25, 3, TO_DATE('2025-02-10', 'YYYY-MM-DD'), 35.75);

INSERT INTO Investors (Betrag, Waehrung_ID, Start_Datum, Gewinn)
VALUES (2000.00, 4, TO_DATE('2025-03-15', 'YYYY-MM-DD'), 100.00);

INSERT INTO Investors (Betrag, Waehrung_ID, Start_Datum, Gewinn)
VALUES (1200.75, 5, TO_DATE('2025-04-01', 'YYYY-MM-DD'), 60.50);

INSERT INTO Investors (Betrag, Waehrung_ID, Start_Datum, Gewinn)
VALUES (300.00, 1, TO_DATE('2025-01-20', 'YYYY-MM-DD'), 10.00);

INSERT INTO Investors (Betrag, Waehrung_ID, Start_Datum, Gewinn)
VALUES (999.99, 3, TO_DATE('2025-02-25', 'YYYY-MM-DD'), 49.99);

INSERT INTO Investors (Betrag, Waehrung_ID, Start_Datum, Gewinn)
VALUES (4500.00, 2, TO_DATE('2025-05-05', 'YYYY-MM-DD'), 225.00);

INSERT INTO Investors (Betrag, Waehrung_ID, Start_Datum, Gewinn)
VALUES (625.50, 4, TO_DATE('2025-06-10', 'YYYY-MM-DD'), 31.25);

INSERT INTO Investors (Betrag, Waehrung_ID, Start_Datum, Gewinn)
VALUES (1500.00, 5, TO_DATE('2025-07-01', 'YYYY-MM-DD'), 75.00);

INSERT INTO Provider (Dienstleistung)
VALUES ('Banking');

INSERT INTO Provider (Dienstleistung)
VALUES ('Trading');

INSERT INTO Provider (Dienstleistung)
VALUES ('Exchange');

INSERT INTO Provider (Dienstleistung)
VALUES ('Staking');

INSERT INTO Provider (Dienstleistung)
VALUES ('Payments'); 

INSERT INTO Staking_Offers (Waehrung_ID, Gewinn, Mindest_frist, MaxVolume)
VALUES (1, 5.00, 30, 10000.0000000000); -- USDT, 5% Ertrag, Mindestlaufzeit 30 Tage, Maximalvolumen 10.000

INSERT INTO Staking_Offers (Waehrung_ID, Gewinn, Mindest_frist, MaxVolume)
VALUES (2, 8.50, 60, 5000.0000000000); 

INSERT INTO Staking_Offers (Waehrung_ID, Gewinn, Mindest_frist, MaxVolume)
VALUES (3, 6.75, 45, 2000.0000000000); 

INSERT INTO Staking_Offers (Waehrung_ID, Gewinn, Mindest_frist, MaxVolume)
VALUES (4, 10.00, 90, 1500.0000000000); 

INSERT INTO Staking_Offers (Waehrung_ID, Gewinn, Mindest_frist, MaxVolume)
VALUES (5, 4.50, 30, 8000.0000000000); 

INSERT INTO Staking_Offers (Waehrung_ID, Gewinn, Mindest_frist, MaxVolume)
VALUES (1, 7.00, 15, 12000.0000000000); 

INSERT INTO Staking_Offers (Waehrung_ID, Gewinn, Mindest_frist, MaxVolume)
VALUES (3, 9.25, 90, 3000.0000000000);

INSERT INTO Staking_Offers (Waehrung_ID, Gewinn, Mindest_frist, MaxVolume)
VALUES (2, 6.00, 30, 7000.0000000000); 

INSERT INTO Staking_Offers (Waehrung_ID, Gewinn, Mindest_frist, MaxVolume)
VALUES (4, 11.50, 120, 2000.0000000000); 

INSERT INTO Staking_Offers (Waehrung_ID, Gewinn, Mindest_frist, MaxVolume)
VALUES (5, 5.25, 20, 10000.0000000000); 


COMMIT;