INSERT INTO "USER" (NAME,EMAIL,PASSWORD,REGISTRERUNGS_DATUM)
VALUES('Test','hui@soset.daniya','12345',SYSDATE);
COMMIT;

INSERT INTO "USER" (NAME,EMAIL,PASSWORD,REGISTRERUNGS_DATUM)
VALUES('Jora','hui@soset2.daniya','12345',SYSDATE);
COMMIT;

INSERT INTO WAEHRUNG (NAME)
VALUES ('USDT');
COMMIT;

INSERT INTO WAEHRUNG (NAME)
VALUES ('BTC');
COMMIT;

INSERT INTO WAEHRUNG (NAME)
VALUES ('ETH');
COMMIT;

INSERT INTO WAEHRUNG (NAME)
VALUES ('SOL');
COMMIT;

INSERT INTO WAEHRUNG (NAME)
VALUES ('XRP');
COMMIT;

INSERT INTO WALLET (USER_ID, KONTOSTAND ,WAEHRUNG_ID,ADRESSE)
VALUES(1,100.000,1,'uhu123123uh131fklqrz');
COMMIT;
