DROP TABLE "USER" CASCADE CONSTRAINTS;
DROP TABLE WALLET CASCADE CONSTRAINTS;
DROP TABLE SWAP CASCADE CONSTRAINTS;
DROP TABLE Staking_Offers CASCADE CONSTRAINTS;
DROP TABLE Staking_Wallet CASCADE CONSTRAINTS;
DROP TABLE Earn CASCADE CONSTRAINTS;
DROP TABLE Waehrung CASCADE CONSTRAINTS;
DROP TABLE Pair CASCADE CONSTRAINTS;
DROP TABLE Transaktionen CASCADE CONSTRAINTS;
DROP TABLE Provider CASCADE CONSTRAINTS;
DROP TABLE Investors CASCADE CONSTRAINTS;
DROP TABLE Offer CASCADE CONSTRAINTS;

COMMIT;
