CREATE OR REPLACE TRIGGER SWAP_KURS
BEFORE INSERT ON SWAP
FOR EACH ROW
BEGIN
    SELECT KURS
    INTO :NEW.WECHSEL_KURS
    FROM PAIR
    WHERE :NEW.FROM_WAEHRUNG_ID=BASECRYPTO_ID and :NEW.TO_WAEHRUNG_ID=QUOTECRYPTO_ID;
    
    UPDATE WALLET
    SET KONTOSTAND=KONTOSTAND-:NEW.BETRAG
    WHERE WALLET.USER_ID=:NEW.USER_ID and WALLET.WAEHRUNG_ID=:NEW.FROM_WAEHRUNG_ID;

    UPDATE WALLET
    SET KONTOSTAND=KONTOSTAND+(:NEW.BETRAG*(SELECT KURS  
                                                    FROM Pair 
                                                    WHERE :NEW.FROM_WAEHRUNG_ID =Pair.BaseCrypto_ID 
                                                    AND PAIR.QUOTECRYPTO_ID= :NEW.To_Waehrung_ID))
    WHERE WALLET.USER_ID=:NEW.USER_ID and WALLET.WAEHRUNG_ID=:NEW.To_Waehrung_ID;

END;