CREATE OR REPLACE TRIGGER SWAP_KURS
BEFORE INSERT ON SWAP
FOR EACH ROW
DECLARE 
    w_KONTOSTAND NUMBER(20,6);
BEGIN
    
    SELECT KURS
    INTO :NEW.WECHSEL_KURS
    FROM PAIR
    WHERE :NEW.FROM_WAEHRUNG_ID = BASECRYPTO_ID 
      AND :NEW.TO_WAEHRUNG_ID = QUOTECRYPTO_ID;

    BEGIN
        SELECT KONTOSTAND 
        INTO w_KONTOSTAND 
        FROM WALLET 
        WHERE :NEW.FROM_WAEHRUNG_ID = WALLET.WAEHRUNG_ID 
          AND WALLET.USER_ID = :NEW.USER_ID;
    END;

    IF w_KONTOSTAND >= :NEW.BETRAG THEN
       UPDATE WALLET
        SET KONTOSTAND = KONTOSTAND - :NEW.BETRAG
        WHERE WALLET.USER_ID = :NEW.USER_ID 
          AND WALLET.WAEHRUNG_ID = :NEW.FROM_WAEHRUNG_ID;

        UPDATE WALLET
        SET WALLET.KONTOSTAND = WALLET.KONTOSTAND + (:NEW.BETRAG * :NEW.WECHSEL_KURS)
        WHERE WALLET.USER_ID = :NEW.USER_ID 
          AND WALLET.WAEHRUNG_ID = :NEW.TO_WAEHRUNG_ID;
    ELSE 
        RAISE_APPLICATION_ERROR(-20002, 'Nicht genug Guthaben für den Swap!');
    END IF;
END;
